config/routes.rb
Rails.application.routes.draw do
  get '/' => 'blogs#main', as: 'blogs'
  get '/blogs/new' => 'blogs#new', as: 'new_blog'
  post '/blogs' => 'blogs#create', as: 'create_blog'
  delete '/blogs:id' => 'blogs#destroy', as: 'delete_blog'
  get '/blogs/:id/edit' => 'blogs#edit', as: 'edit_blog'
  patch '/blogs/:id' => 'blogs#update'
  get '/blogs/:id' => 'blogs#show'
  # resources :blogs, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  root 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence: true
  validates :title, presence: true, uniqueness: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    render 'main.html.erb'
  end

  def main
    @blogs = Blog.all
    render 'main.html.erb'
  end

  def show
    @blog = Blog.find(params[:id])
    render 'blog_show.html.erb'
  end

  def new
    @blog = Blog.new
  end

  def create
      @blog = Blog.create(blog_params)
      if @blog.valid?
        redirect_to '/'
      else
        redirect_to '/blogs/new'
      end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to '/'
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    if @blog.valid?
      redirect_to blogs_path
    else
      redirect_to edit_blog_path(@blog)
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
    @blogs = Blog.all
    render 'main.html.erb'
  end

  def show
    @blog = Blog.find(params[:id])
    render 'blog_show.html.erb'
  end

  def new
    @blog = Blog.new
  end

  def create
      @blog = Blog.create(blog_params)
      if @blog.valid?
        redirect_to '/'
      else
        redirect_to '/blogs/new'
      end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to '/'
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/blogs/blog_show.html.erb
<h2>This blog: </h2>
<h3>Title:
  <%= @blog.title %>
</h3>
<br>
<p>Content: </p>
<%= @blog.content %>
<br>
<br>
<%= link_to 'Update this blog', edit_blog_path(@blog) %>
<br>
<br>
<%= link_to 'Delete this blog', delete_blog_path(@blog), method: :delete, data: {confirm: 'Are you sure?'} %>
<br>
<br>
<%= link_to 'Return to list', blogs_path %>

app/views/blogs/edit.html.erb
<h2>Edit blog post</h2>

<%= form_with model: @blog, method: :patch, url: "/blogs/#{@blog.id}", local: true do |form| %>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <br>
    <br>
    <%= form.label :content %>
    <br>
    <%= form.text_field :content %>
    <br>
    <br>
    <%= form.submit 'Update Blog' %>
<%end%>
<br>
<br>
<p class="link"><%= link_to 'Return to list', blogs_path %></p>

app/views/blogs/main.html.erb
<h2>Blog page<h2>
<% @blogs.each do |blog| %>
  <%= link_to blog.title, "/blogs/#{blog.id}" %>
  <br>
<%end%>
<br>
<%=  link_to 'Create new blog', new_blog_path %>

app/views/blogs/new.html.erb
<h2> Create a new blog post</h2>
<%= form_with model: @blog, url: create_blog_path, local: true do |form| %>
<%= form.label :title %>
<br>
<%= form.text_field :title %>
<br>
<br>
<%= form.label :content %>
<br>
<%= form.text_field :content %>
<br>
<br>
<%= form.submit 'Add Blog' %>
<%end%>
<br>
<br>
<p class="link"><%= link_to 'Return to list', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/blog_show.html.erb
<h2>This blog: </h2>
<h3>Title:
  <%= @blog.title %>
</h3>
<br>
<p>Content: </p>
<%= @blog.content %>
<br>
<br>
<%= link_to 'Update this blog', edit_path(@blog) %>
<br>
<br>
<%= link_to 'Delete this blog', delete_path(@blog), method: :delete, data: {confirm: 'Are you sure?'} %>
<br>
<br>
<%= link_to 'Return to list', main_path %>

app/views/main/edit.html.erb
<h2>Edit blog post</h2>

<%= form_with model: @blog, method: :patch, local: true do |form| %>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <br>
    <br>
    <%= form.label :content %>
    <br>
    <%= form.text_field :content %>
    <br>
    <br>
    <%= form.submit 'Update Blog' %>
<%end%>
<br>
<br>
<p class="link"><%= link_to 'Return to list', blogs_path %></p>

app/views/main/main.html.erb
<h2>Blog page<h2>
<% @blogs.each do |blog| %>
  <%= link_to blog.title, "/blogs/#{blog.id}" %>
  <br>
<%end%>
<br>
<%=  link_to 'Create new blog', new_path %>

app/views/main/new.html.erb
<h2> Create a new blog post</h2>
<%= form_with model: @blog, local: true do |form| %>
<%= form.label :title %>
<br>
<%= form.text_field :title %>
<br>
<br>
<%= form.label :content %>
<br>
<%= form.text_field :content %>
<br>
<br>
<%= form.submit 'Add Blog' %>
<%end%>
<br>
<br>
<p class="link"><%= link_to 'Return to list', main_path %></p>